# Makefile excercise of the UHPC 2020
# IT4Innovations, VSB-TUO

# Be aware of the parameters order, may cause a compilation error

.PHONY: 

CFLAGS=-std=
APPDIR=
LIBDIR=

lib:
	@echo LIB

static:
	@echo STATIC

dynamic:
	@echo DYNAMIC

start:
	@echo START
	
stop:
	@echo STOP

run:
	bin/start
	sleep 1
	bin/stop

clean:
	rm -rf bin/* lib/* *.o 

